name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Zip build outputs
      run: zip -r artifacts ./app/build/outputs/apk/debug
    - name: Upload asset to release
      uses: actions-github/upload-to-release@v1.0.0
      with:
        # Input file
        file: ./artifacts
        # File type
        type: application/zip
